---
name: Build Workflow

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ⏬ Checkout repo
        uses: actions/checkout@v7

      - name: 🔄 Init Cache
        uses: nmerget/npm-cache-action@main

      - name: 🔨 Build
        run: npm run build

      - name: ⏫ Upload build
        uses: nmerget/upload-gzip-artifact@main
        with:
          name: build
          path: dist
